djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth import views

from django.urls import path, include

from userextend.forms import AuthenticationNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proschool.urls')),
    path('', include('students.urls')),
    path('', include('teacher.urls')),
    path('', include('headmaster.urls')),

    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),

    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                        document_root=settings.MEDIA_ROOT)

teacher/urls.py
from django.urls import path
from teacher import views

urlpatterns = [
    path('create-teacher/', views.TeacherCreateView.as_view(), name='create_teacher'),
    path('list-of-teachers/', views.TeacherListView.as_view(), name='list_of_teachers'),
    path('update-teacher/<int:pk>/', views.TeacherUpdateView.as_view(), name='update_teacher'),
    path('delete-teacher/<int:pk>/', views.TeacherDeleteView.as_view(), name='delete_teacher'),
    path('inactivate-teacher/<int:pk>/', views.inactivate_teacher, name='inactivate_teacher'),
    path('create-homework/', views.HomeworkCreateView.as_view(), name='create_homework'),
    path('list-of-homeworks/', views.HomeworkListView.as_view(), name='list_of_homeworks'),
    path('update-homework/<int:pk>/', views.TeacherUpdateView.as_view(), name='update_homework'),
    path('delete-homework/<int:pk>/', views.TeacherDeleteView.as_view(), name='delete_homework'),

]

headmaster/models.py
from django.db import models

from teacher.models import Teacher


# Create your models here.
class Classroom(models.Model):
    classroom_name = models.CharField(max_length=20)
    class_master = models.ForeignKey(Teacher, on_delete=models.CASCADE, blank=True, null=True)

    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.classroom_name

students/models.py
from django.db import models
from headmaster.models import Classroom

# Create your models here.




class Student(models.Model):

    gender_options = (('male', 'Male'), ('female', 'Female'))

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    student_id = models.IntegerField(unique=True)
    age = models.IntegerField
    email = models.EmailField(max_length=80)
    description = models.CharField(max_length=500)
    gender = models.CharField(max_length=10, choices=gender_options)
    current_class = models.ForeignKey(Classroom, on_delete=models.CASCADE, null=True)

    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

teacher/models.py
from django.db import models


# Create your models here.



class Teacher(models.Model):

    school_subject = (('literature', 'Literature'), ('math', 'Math'), ('history', 'history'), ('biology', 'Biology'),
                      ('physiscs', 'Physics'), ('english', 'English'), ('geography', 'Geography'))
    school_level = (('primary', 'Primary'), ('gymnasium', 'Gymnasium'), ('highschool', 'Highschool'))

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=80)
    phone_number = models.CharField(max_length=14)
    education_level = models.CharField(max_length=50, choices=school_level)
    course = models.CharField(max_length=50, choices=school_subject)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Homework(models.Model):

    homework_title = models.CharField(max_length=150)
    homework_description = models.TextField(max_length=2000)
    due_date = models.DateField()
    discipline = models.CharField(max_length=50, choices=Teacher.school_subject)
    classroom = models.ForeignKey('headmaster.Classroom', on_delete=models.CASCADE, null=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)

    image = models.ImageField(upload_to='images/', blank=True, null=True)
    file = models.FileField(upload_to='file/', blank=True, null=True)

    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.homework_title}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/background.css' %}">
</head>
<body>
{#<h1 class="edit_h1">Hello, Andrei!</h1>#}
{#<img src="{% static 'images/download.jpg' %}" alt="imagine" width="200">#}
{% include 'navbar.html' %}


<div class="images">
    <div class="image">
        <img src="{% static 'images/download.jpg' %}" alt="imagine" width="800">
    </div>
</div>


{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>

{#<script src="{% static 'js/my_script.js' %}"></script>#}
</body>
</html>

templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .edit_h3{
            color:red
        }
    </style>
</head>
<body>

<h3 class="edit_h3">Hello, {{ fullname }}</h3>
<p>Your username is: {{ username }}</p>
<button>Click here</button>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage' %}">
            {% load static %}
            <img src="{% static 'images/logo.png' %}" alt="Proschool" , width="150">

        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    {% if perms.teacher.add_teacher or perms.teacher.view_list_of_teachers or perms.teacher.create_homework or perms.teacher.view_list_of_homeworks %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Teachers
                            </a>
                            <ul class="dropdown-menu">
                                {% if perms.teacher.view_list_of_teachers %}
                                    <li><a class="dropdown-item" href="{% url 'list_of_teachers' %}">List of
                                        teachers</a></li>
                                {% endif %}
                                {% if perms.teacher.add_teacher %}
                                    <li><a class="dropdown-item" href="{% url 'create_teacher' %}">Create teacher</a>
                                    </li>
                                {% endif %}
                                {% if perms.teacher.create_homework %}
                                    <li><a class="dropdown-item" href="{% url 'create_homework' %}">Create homework</a>
                                    </li>
                                {% endif %}
                                {% if perms.teacher.view_list_of_homeworks %}
                                    <li><a class="dropdown-item" href="{% url 'list_of_homeworks' %}">List of
                                        Homeworks</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}

                    {% if perms.students.add_student or perms.students.view_list_of_students or perms.students.view_list_of_homeworks %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Students
                            </a>
                            <ul class="dropdown-menu">
                                {% if perms.students.view_list_of_students %}
                                    <li><a class="dropdown-item" href="{% url 'list_of_students' %}">List of
                                        students</a></li>
                                {% endif %}
                                {% if perms.students.add_student %}
                                    <li><a class="dropdown-item" href="{% url 'create_student' %}">Create student</a>
                                    </li>
                                {% endif %}
                                {% if perms.students.view_list_of_homeworks %}
                                    <li><a class="dropdown-item" href="{% url 'student_homework_list' %}">Homeworks</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}
                    {% if perms.headmaster.view_list_of_classrooms or perms.headmaster.add_classroom %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Classrooms
                            </a>
                            <ul class="dropdown-menu">
                                {% if perms.headmaster.view_list_of_classrooms %}
                                    <li><a class="dropdown-item" href="{% url 'list_of_classrooms' %}">List of
                                        classrooms</a>
                                    </li>
                                {% endif %}
                                {% if perms.headmaster.add_classroom %}
                                    <li><a class="dropdown-item" href="{% url 'create_classroom' %}">Create
                                        classroom</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}
                {% endif %}

            </ul>
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        My profile, {{ user.username }}
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>

                    </ul>
                </div>

                {% if perms.students.search_student %}
                <form method="get" class="d-flex" role="search" action="{% url 'search' %}">
                    <input class="form-control me-2" type="search" name="search" placeholder="Search"
                           aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                    {% endif %}
            {% else %}
                <div>
                    <a href="{% url 'login' %}" class="btn btn-outline-dark">Login</a>
                    <a href="{% url 'create_user' %}" class="btn btn-outline-danger">Sign up</a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>